spring.application.name=SWP391_QuitSmoking_BE
spring.main.allow-circular-references=true

spring.datasource.url=jdbc:postgresql://localhost:5432/QuitSmokingDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

app.environment=development
app.base-url.development=http://localhost:8080
app.base-url.staging=https://staging-api.yourapp.com
app.base-url.production=https://api.yourapp.com

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình VNPay
vnpay.tmn-code=ZA6FG78P
vnpay.hash-secret=Z25RB7TCSI1YRL6BXEZSORFP042ZQ8V8
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/vnpay/callback
vnpay.timeout-minutes=15
vnpay.max-amount=50000000
vnpay.min-amount=10000
